version: "3.8"
services:
  backend:
    image: backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: backend-dev
    ports:
      - 80:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=trustcar
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "trustcar@trustcar.fi"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - 16543:80

volumes:
  postgres-data:
    driver: local