version: "3.8"
services:
  backend:
    image: backend-dev
    environment:
      - DATABASE_URL=postgresql://trustcar:password@postgres:5432/trust_car_dev_db?schema=public
      - JWT_SECRET=mysecret
      - PORT=8080
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: backend-dev
    ports:
      - 80:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=trustcar
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

