name: Lint and Deploy Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint 
        run: npm run lint

      - name: Test
        run: npm run test

  deploy:
    permissions: write-all
    needs: [lint_and_test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to production
        run: echo "Deploying to production"

      - name: Deploy via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: echo "$SSH_PRIVATE_KEY"
      - name: Run Command via SSH
        uses: appleboy/ssh-action@master
        with:
          host: carpass.fi
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd trustcar/trustcar-back/
            git checkout main
            git pull
